### PR TITLE
update Screenshots for readme

### PR DESCRIPTION
**Pull request by ArshdeepSingh3-eaton**
Fixes # .
Updated the Screenshots for the components

#### Changes proposed in this Pull Request:
- 
- 
- 

#### Screenshots / Screen Recording (if applicable)
-

#### To Test:
- 

#### Any specific feedback you are looking for?
-

### CODE REVIEW

**Review by ektaghag-eaton — COMMENTED** [review]
Can we change image there is black shadow on left side of image  
Screenshot 2024-01-03 at 2 37 38 PM

**Comment by ektaghag-eaton** [comment]
> Can we change image there is black shadow on left side of image Screenshot 2024-01-03 at 2 37 38 PM

On local image looks correct.

**Comment by huayunh** [comment]
can you make the build pass?

**Comment by huayunh** [comment]
Can you see if you can make the circle ci build to pass?

**Review by huayunh — COMMENTED** [review]
* What Ekta commented
* Chips image is way too small
* Can you update the collapsible header layout too
* In the Hero component, icons feel very small compared to the text
* Use [this image](https://private-user-images.githubusercontent.com/8997218/293961330-6a20e5c7-247a-4137-bb6c-cc4b3e404a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyOTcwNjgsIm5iZiI6MTcwNDI5Njc2OCwicGF0aCI6Ii84OTk3MjE4LzI5Mzk2MTMzMC02YTIwZTVjNy0yNDdhLTQxMzctYmI2Yy1jYzRiM2U0MDRhOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMTU0NjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjAyYjk5NzE5ZjJhZTc1YmJmMzhkMTVmOTMwMDBjYzRiMGMzNmRiZTc0ODcyNWE4N2NiMGYwZTQxN2JlNjVkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6H-gDjZk1QykAqbi3IqKmIaRcHM2DRM3oIi1AKm_xj0) I just made for list item tag
* Mobile stepper:
  * The default "dot" variant should be captioned too. Don't just leave it there and let adopters infer what variant it is 
  * Ensure your images are aligned / showing up on a second line. Verify that by checking the [actual markdown file](https://github.com/etn-ccis/blui-react-native-component-library/blob/bug/blui-5060-UpdateReadme/docs/MobileStepper.md).
* Overline image too big

**Review by huayunh — APPROVED** [review]

**Pull request merged**
