### PR TITLE
Updated the default icon direction to ltr

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes # BLUI-4877 #180 

#### Changes proposed in this Pull Request:
- Updated the condition of flip icon

#### Screenshots / Screen Recording (if applicable)
- 
Screenshot 2023-11-02 at 3 26 04 PM

#### To Test:
- yarn start
- Update the device setting using I18nManager (rtl/ ltr)
- Pass the direction in search icon in header (rtl / ltr / auto/ undefined)
- It should flip icon in the following condition (Y - Flip / N - Don't)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/e0661236/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/e0661236/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

device setting | icon direction |   |   |  
-- | -- | -- | -- | --
  | ltr | rtl | auto | undefined
LTR | N | Y | N | N
RTL | N | Y | Y | N

</body>

</html>

#### Any specific feedback you are looking for?
-

### CODE REVIEW

**Review by huayunh — COMMENTED** [review]
Code change looks logically sound. I did not run the project locally. 

Please remember to update the changelog and readme (and JSDocs too if applicable_

**Comment by huayunh** [comment]
Eh. My PR comment above mentioned 3 things:

1. changelog
2. readme
3. JSDocs

**Review by ektaghag-eaton — APPROVED** [review]
Changes are working fine.

**Icon direction: auto and device setting RTL**
Screenshot 2023-11-06 at 6 27 17 PM

Screenshot 2023-11-06 at 6 27 09 PM

**Icon direction: rtl and device setting RTL**
Screenshot 2023-11-06 at 6 34 11 PM
Screenshot 2023-11-06 at 6 33 30 PM

**Icon direction: undefined and device setting RTL**

Screenshot 2023-11-06 at 6 37 57 PM
Screenshot 2023-11-06 at 6 37 52 PM

**Review by huayunh — APPROVED** [review]

**Review by huayunh — COMMENTED** [review]
Looks good. See if you can get the lint error fixed before you merge

**Pull request merged**
