### PR TITLE
Update Collapsed Header

### PR DESCRIPTION
**Pull request by ArshdeepSingh3-eaton**
BLUI-4364

#### Changes proposed in this Pull Request:
- Updated the Collapsed Header Component
- 
- 

#### Screenshots / Screen Recording (if applicable)
https://github.com/etn-ccis/blui-react-native-component-library/assets/144440086/0114309b-3cbd-4fbb-974a-5292b4269db7

#### To Test:
- 

#### Any specific feedback you are looking for?
-

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
Not sure if I should be adding or removing anything with test instructions from above but I see issue with dynamic variant not working for me. The static variant seems ok.


https://github.com/etn-ccis/blui-react-native-component-library/assets/119693939/03ae286f-ced6-4c08-a5cb-af8b9adf25b3

**Comment by ArshdeepSingh3-eaton** [comment]
there needs to be some changes that needs to be made in **showcase/app.tsx** as specified in the following PR [https://github.com/etn-ccis/blui-react-native-showcase-demo/pull/92](url)

**Comment by JeffGreiner-eaton** [comment]
> there needs to be some changes that needs to be made in **showcase/app.tsx** as specified in the following PR [https://github.com/etn-ccis/blui-react-native-showcase-demo/pull/92](url)

don't understand. The test instructions are to return nothing. Its been a while since I've looked at this and I need specific instructions.

**Comment by ArshdeepSingh3-eaton** [comment]
Replace the showcase/app.tsx with the following code
`import React from 'react';
//import type { PropsWithChildren } from 'react';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { SafeAreaView, ScrollView, StatusBar, /*StyleSheet, Text,*/ useColorScheme, View } from 'react-native';

import { Colors } from 'react-native/Libraries/NewAppScreen';
import { KitchenSink } from './components/kitchen-sink';


function App(): JSX.Element {
    const isDarkMode = useColorScheme() === 'dark';

    const backgroundStyle = {
        backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
    };

    return (
                        <KitchenSink />
    );
}


export default App;
`

**Comment by JeffGreiner-eaton** [comment]
This looks good just fix the lint error on Colors

**Review by JeffGreiner-eaton — APPROVED** [review]

**Pull request merged**
