### PR TITLE
Feature/4376 user menu md3

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes # BLUI-4376

#### Changes proposed in this Pull Request:
- Added UserMenu component using MD3 theme

#### Screenshots / Screen Recording (if applicable)
https://github.com/etn-ccis/blui-react-native-component-library/assets/120575281/e5ed7458-fe8c-4fbd-81fb-7fea9e1e5a68

#### To Test:
- Checkout [feature/4376-user-menu-kitchen-sink-example](https://github.com/etn-ccis/blui-react-native-showcase-demo/tree/feature/4376-user-menu-kitchen-sink-example) branch in showcase
- yarn start
- In UserMenu, click on **JS** avatar
- Should open Bottom Sheet

#### Any specific feedback you are looking for?
- Please open https://github.com/etn-ccis/blui-react-native-showcase-demo/pull/93 once this PR gets merged.

### CODE REVIEW

**Review by ektaghag-eaton — APPROVED** [review]
Changes looks good 👍

**Review by JeffGreiner-eaton — APPROVED** [review]
this looks good to me, but menuItems colors are darker than before...

image

**Comment by huayunh** [comment]
I think the menu item is picking up the correct color from the theme (the new theme's primary text color `onSurface` is significantly darker compared to its previous version). I do find the email address color to be really light though.

image

**Comment by huayunh** [comment]
Also this color difference (I think this is out of scope for this story; feel free to log an issue):

image

**Comment by surajeaton** [comment]
> I think the menu item is picking up the correct color from the theme (the new theme's primary text color `onSurface` is significantly darker compared to its previous version). I do find the email address color to be really light though.
> 
> image

`Email Address` is a subtitle from InfoListItem. Each menu item in the example is info list item. We may need to update the color of subtitle there

**Comment by surajeaton** [comment]
> > I think the menu item is picking up the correct color from the theme (the new theme's primary text color `onSurface` is significantly darker compared to its previous version). I do find the email address color to be really light though.
> > image
> 
> `Email Address` is a subtitle from InfoListItem. Each menu item in the example is info list item. We may need to update the color of subtitle there

Logged an issue.

**Comment by surajeaton** [comment]
> Also this color difference (I think this is out of scope for this story; feel free to log an issue):
> 
> image



> Also this color difference (I think this is out of scope for this story; feel free to log an issue):
> 
> image

Logged an issue. https://github.com/etn-ccis/blui-react-native-component-library/issues/414

**Pull request merged**
