### PR TITLE
Added support for all the scroll components (option 4)

### LINKED ISSUE #218: CollapsibleHeaderLayout should support other scroll containers
#### Describe the desired behavior
The user should be able to use the CollapsibleHeaderLayout with any type of scrollable container they wish (ScrollView, KeyboardAvoidingScrollView, FlatList, SectionList).

#### Describe the current behavior
The CollapsibleHeaderLayout uses a hard-coded ScrollView element. 

#### Is this request related to a current issue?
This is something that we identified during initial implementation as a likely area that we would want to expand support. It has recently come up within the CRDS WiFi Wiring team.

#### Additional Context

This is particularly an issue because React Native doesn't let you render a FlatList inside of a ScrollView. So if a team (like CRDS) wants to use a FlatList to display their content (because it does virtualization and offers better performance), they can't and have to use the ScrollView which offers no optimization or performance.

There are a couple of ways we can do this:
1. Let the user pass in the element themselves. We would then just take the first child element, add the necessary props to it for use in the CollapsibleHeaderLayout (ref, scrollThrottle, etc.) and wrap the children in an animated view.
2. Restrict which options are allowed and expose a prop for selecting which item to use as the scroll container. Then expose another prop that will let the user spread props to the scroller (particularly important if using a flatlist or a sectionlist). 

Number 1 seems like the more graceful approach, but in my initial exploration, it caused issues with performance because the React.clone function was getting called too often. Number 2 introduces a lot of complexity to the typings.

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes #218 

#### Changes proposed in this Pull Request:
- Added scroll component and prop and also as a children
- We are giving user control to handle scroll

#### Screenshots / Screen Recording (if applicable)
-
Screenshot 2023-03-10 at 4 06 51 PM

#### To Test:
- yarn build
- Generate react native cli project
- Copy the dist folder contents in blui react native repo to node_modules/react-native-components of cli generated project
- Paste this in App.tsx of cli generated project 
- https://eaton-my.sharepoint.com/:o:/p/surajakarambe/EnIhpVERDClCgFWCzsNVwPABCbj-y3kl7UBtpFb3iqUoWQ?e=0yx4Qr

#### Any specific feedback you are looking for?
- We are using option 4 which is suggested in the issue.
- **Note: If you are using cli generated project to test this, you need to comment out line 67 of headerContent.tsx as cli generated project uses react-native-paper v5**

### CODE REVIEW

**Comment by surajeaton** [comment]
> Do you have documentation around these updates to explain how an end user would use this?

Nope. Do we want documentation ? @daileytj @joebochill

**Comment by daileytj** [comment]
@surajeaton 
- This code snippet doesn't work.
- Yes, there should be documentation, otherwise, no one would know how to use it.
- I shouldn't have to modify the core code for this to work... The cli-generated project uses react-native-paper v4.7.2

**Comment by JeffGreiner-eaton** [comment]
@surajeaton should your code snippet be working now with last commit now?

**Comment by surajeaton** [comment]
> @surajeaton should your code snippet be working now with last commit now?

No @JeffGreiner-eaton My last commit was to address the default condition.

Here's link to the code to paste new App.tsx of new cli generated project

**Comment by JeffGreiner-eaton** [comment]
I was able to run the latest code snippet you provided. This might be running better for some but on android it really has some performance issues as you can see in the video...It is working and just needs styles applied to keep the bleed from happening.


https://user-images.githubusercontent.com/119693939/226732926-9559ab7c-6c4e-4bc7-b0eb-fea07e450c28.mov

**Comment by joebochill** [comment]
> I was able to run the latest code snippet you provided. This might be running better for some but on android it really has some performance issues as you can see in the video...It is working and just needs styles applied to keep the bleed from happening.

@JeffGreiner-eaton do you see the same performance issue on Android with the current (latest published) version of the CollapsibleHeaderLayout? Or does this update make it worse?

**Comment by daileytj** [comment]
https://user-images.githubusercontent.com/13989985/226995141-439d19bc-2726-401f-9d8a-f1ce8a884cf1.mov

I tested this with 22 items in this list and cannot scroll any further than item 15-ish

**Comment by JeffGreiner-eaton** [comment]
> I tested this with 22 items in this list and cannot scroll any further than item 15-ish

any results on Android?

**Comment by daileytj** [comment]
> > I tested this with 22 items in this list and cannot scroll any further than item 15-ish
> 
> any results on Android?


https://user-images.githubusercontent.com/13989985/227015040-f5526ec3-1eda-4d99-8bea-03ce65e9956d.mov

**Comment by surajeaton** [comment]
> @joebochill @JeffGreiner-eaton Can you take a look at this again to make sure the docs are appropriate and everything runs as expected with the refactoring that just got merged in.

@JeffGreiner-eaton @joebochill Can you please review.

**Comment by surajeaton** [comment]
@JeffGreiner-eaton @huayunh Can you please review ?

**Comment by huayunh** [comment]
My limited knowledge of React Native is insufficient to review this skillful PR. All I can tell is the documentation seems fine, but nothing more than that.

**Comment by JeffGreiner-eaton** [comment]
It runs completely better now, big difference. I can view all items & performance on android seems good.

https://user-images.githubusercontent.com/119693939/230434723-fbab4594-90c6-4609-a831-b1eaad8bb9d9.mov

**Comment by JeffGreiner-eaton** [comment]
Example from CollapsibleHeaderLayout.md


https://user-images.githubusercontent.com/119693939/230440369-8b7f3d57-a1f8-42a9-85a8-2bbf669ab326.mov

**Review by JeffGreiner-eaton — APPROVED** [review]
seems good to me

**Pull request merged**
