### PR TITLE
fix drawer issue

### PR DESCRIPTION
**Pull request by ArshdeepSingh3-eaton**
Fixes # .
fixed drawer navitem icons not aligning

#### Changes proposed in this Pull Request:
- 
- 
- 

#### Screenshots / Screen Recording (if applicable)
-
Screenshot 2024-02-07 at 2 07 44 PM

#### To Test:
- 

#### Any specific feedback you are looking for?
-

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
can you link the issue for this

**Comment by JeffGreiner-eaton** [comment]
Can you provide before and after screen shots for this. This is what I see in dev and I can't see the difference
image

**Comment by ektaghag-eaton** [comment]
We don't need to fix anything. For center align we need to pass like this https://github.com/etn-ccis/blui-react-native-showcase-demo/blob/dev/router/NavigationDrawer.tsx#L69

**Comment by joebochill** [comment]
> We don't need to fix anything. For center align we need to pass like this https://github.com/etn-ccis/blui-react-native-showcase-demo/blob/dev/router/NavigationDrawer.tsx#L69

That's not correct — the `iconAlign` property of the InfoListItem is for horizontal alignment of the icon in it's 40px wide container. It is NOT for the vertical alignment (there is no case I can think of where we would actually want to have anything other than center alignment vertically).

**Comment by JeffGreiner-eaton** [comment]
I did fresh clone and see the difference now.
- dev branch
Pasted Graphic 7
Pasted Graphic 8

- This branch
Pasted Graphic 14
Pasted Graphic 15

**Review by JeffGreiner-eaton — APPROVED** [review]

**Pull request merged**
