### PR TITLE
Removed typography and icon wrapper references

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes # BLUI-4350

#### Changes proposed in this Pull Request:
- Removed typography and icon wrapper

#### Screenshots / Screen Recording (if applicable)
-

#### To Test:
- 

#### Any specific feedback you are looking for?
-

### CODE REVIEW

**Review by huayunh — COMMENTED** [review]
What do you think if we keep the old Typography readme around, but mark the content as deprecated, with an additional note on how to use the typography styles in React Native Paper v5?

**Comment by joebochill** [comment]
> What do you think if we keep the old Typography readme around, but mark the content as deprecated, with an additional note on how to use the typography styles in React Native Paper v5?

Typography is not deprecated, it's removed entirely. I don't think it makes sense to document a component that does not exist, nor to duplicate usage information that already exists in RNP documentation. The migration guide should mention the removal of the component and link to the RNP replacement (mapping from old components to new components/variants if possible).

**Comment by huayunh** [comment]
@joebochill What's your opinion on [IconWrapper.md](https://github.com/brightlayer-ui/react-native-component-library/blob/dev/docs/IconWrapper.md)? We kept it because we think some adopters would find this historical version helpful. We even have a remark linking to it [in the current React Native docs](https://brightlayer-ui-components.github.io/react-native/?path=/info/components-documentation--icons).

**Comment by joebochill** [comment]
> in the current React Native docs

I would say the same thing...if it doesn't exist, it shouldn't be part of the core docs. Things that are removed should be noted in the changelog/migration guide and if we need to refer to historical docs, we can point to historic commits from there.

**Comment by huayunh** [comment]
Ok, as long as everything stays consistent. We can get rid of both IconWrapper related stuff and this typography thing

**Review by ektaghag-eaton — COMMENTED** [review]
Remove IconWrapper reference from 

https://github.com/etn-ccis/blui-react-native-component-library/pull/483/files#diff-b1b786098c4fa4ff2f6eea4aa4816179b09676a5b43c6b2f3c3f6920dc9bfe7bR76

**Comment by ektaghag-eaton** [comment]
> Remove IconWrapper reference from
> 
> https://github.com/etn-ccis/blui-react-native-component-library/pull/483/files#diff-b1b786098c4fa4ff2f6eea4aa4816179b09676a5b43c6b2f3c3f6920dc9bfe7bR76

Removed here https://github.com/etn-ccis/blui-react-native-component-library/pull/479/files#diff-b1b786098c4fa4ff2f6eea4aa4816179b09676a5b43c6b2f3c3f6920dc9bfe7b

**Review by ektaghag-eaton — APPROVED** [review]

**Pull request merged**
