### PR TITLE
Feature/handle extra large font size accessibility

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes # BLUI-3647

#### Changes proposed in this Pull Request:
- Updated component to use font scale props

#### To Test:
- yarn build
- Checkout **bugfix/3647-224-handle-extra-large-accessibility-on-ios** branch in showcase
- cd demos/showcase
- cd ios && pod install
- cd .. && yarn run ios
- You can set the value for MAX_FONT_SCALE, MIN_FONT_SCALE, DISABLE_FONT_SCALE in demos/showcase/constants/index.ts for testing

**Note: Changelog links to new GHE repo has been covered in https://github.com/etn-ccis/blui-react-native-component-library/pull/314**

### CODE REVIEW

**Comment by daileytj** [comment]
Here are some screenshots of what it looks like on my local when I disable font scaling in the showcase, but max out the size in the phone accessibility font size settings. I am on the `feature/handle-extra-large-font-size-accessibility` components branch using the `bugfix/3647-224-handle-extra-large-accessibility-on-ios` showcase branch. Should I be doing something else to match the image you shared above? 

Simulator Screen Shot - iPhone 12 - 2022-12-14 at 14 13 54
Simulator Screen Shot - iPhone 12 - 2022-12-14 at 14 13 34
Simulator Screen Shot - iPhone 12 - 2022-12-14 at 14 13 24

**Comment by bkarambe** [comment]
> Here are some screenshots of what it looks like on my local when I disable font scaling in the showcase, but max out the size in the phone accessibility font size settings. I am on the `feature/handle-extra-large-font-size-accessibility` components branch using the `bugfix/3647-224-handle-extra-large-accessibility-on-ios` showcase branch. Should I be doing something else to match the image you shared above?
> 
> Simulator Screen Shot - iPhone 12 - 2022-12-14 at 14 13 54 Simulator Screen Shot - iPhone 12 - 2022-12-14 at 14 13 34 Simulator Screen Shot - iPhone 12 - 2022-12-14 at 14 13 24

@daileytj Yes, the screen shots you took make sense. Also, you're currently using the correct branches. Do not refer to the image in description. I will get it updated.

**Comment by daileytj** [comment]
Should the Header and DrawerHeader components render as they in the screenshots I provided despite disabling font scaling?

**Comment by bkarambe** [comment]
> Should the Header and DrawerHeader components render as they in the screenshots I provided despite disabling font scaling?

Yes. Header and drawer header should render the same as they are in the screenshots.

**Review by daileytj — APPROVED** [review]
I'm still slightly concerned about the drawer header size that is depicted in the screenshots, but everything else is fine. If this is the intended functionality then this is good to go.

**Comment by daileytj** [comment]
Before you merge this @bkarambe, can you update the package version so that we can publish a beta to test with the showcase?

**Comment by bkarambe** [comment]
Sure @daileytj

**Comment by bkarambe** [comment]
> I'm still slightly concerned about the drawer header size that is depicted in the screenshots, but everything else is fine. If this is the intended functionality then this is good to go.

We will wait for @joebochill 's view on this.

**Comment by joebochill** [comment]
Trust your gut @daileytj — the Header is definitely not correct. The font sizes look right, but the height of the Header is not (note that what you are seeing in the screen shots is the collapsed size, not the expanded size...so its WAAAAY off). With scaling disabled it should look exactly the same as if you had you system font size set to 1:

image
image

@bkarambe — the logic for this update should be affecting anywhere that we use fontscale (including heights), not just the font sizes themselves, otherwise things will look out of proportion like this.

**Comment by bkarambe** [comment]
> Trust your gut @daileytj — the Header is definitely not correct. The font sizes look right, but the height of the Header is not (note that what you are seeing in the screen shots is the collapsed size, not the expanded size...so its WAAAAY off). With scaling disabled it should look exactly the same as if you had you system font size set to 1:
> 
> image
> 
> image
> 
> @bkarambe — the logic for this update should be affecting anywhere that we use fontscale (including heights), not just the font sizes themselves, otherwise things will look out of proportion like this.

Noted. Will do the suggested changes.

**Comment by bkarambe** [comment]
> Before you merge this @bkarambe, can you update the package version so that we can publish a beta to test with the showcase?

Updated

**Comment by bkarambe** [comment]
@joebochill @daileytj Please review

**Review by joebochill — COMMENTED** [review]
Code changes look good...i'll leave it to Tom to verify everything looks right when you run it.

**Comment by jeffvg** [comment]
wondering how far is tooo far when it breaks

image

**Comment by joebochill** [comment]
> wondering how far is tooo far when it breaks

Your first picture looks like the Toolbar from RNP which is not affected by the Context provider we use for our components (it’s not possible). If you want it to look right it would need to be a customization in the showcase demo itself. 

The second screenshot I’m not sure what you’re showing (what settings are you using?). It looks like maybe you’ve got the system font set to very large, capped by a max value in the provider? If that’s the case, then it looks like the header is too tall. But I don’t know if you have customized the height of the header or if it’s open or closed. More details needed.

**Comment by joebochill** [comment]
@jeffvg I just ran a fresh clone and can't reproduce what you're seeing by modifying the fontscale values...please provide reproduction steps if that's still an issue.

**Comment by jeffvg** [comment]
> @jeffvg I just ran a fresh clone and can't reproduce what you're seeing by modifying the fontscale values...please provide reproduction steps if that's still an issue.

I didn't adjust any code and just used larger font setting on device.

**Comment by joebochill** [comment]
> I didn't adjust any code and just used larger font setting on device.

Do you have the correct branch in the showcase and pulled all the latest changes?

**Comment by jeffvg** [comment]
> > > I didn't adjust any code and just used larger font setting on device.
> > 
> > 
> > Do you have the correct branch in the showcase and pulled all the latest changes?
> 
> this is my showcase branch - cloning fresh again just incase image

for some reason I didn't have the latest changes for showcase and doing pull didn't fetch for me. So now on a fresh clone I have the updated index and seems to be good now....
image

**Review by daileytj — APPROVED** [review]

**Comment by daileytj** [comment]
@bkarambe This looks good so far. Can you update the `ThemesComponents` as well?

**Comment by bkarambe** [comment]
> @bkarambe This looks good so far. Can you update the `ThemesComponents` as well?

I have checked the themed components, but found that we have updated the 3 components where we can pass the font scale related props. Can you please let me know, if I am missing some component?

**Comment by joebochill** [comment]
The Chevron in the InfoListItem should be something that we have control over...it looks like it's scaling even when scaling is disabled or capped at a small value.

The Buttons, @bkarambe is right...there's no way for us to cap them unfortunately because of how they are implemented by RNP.

There is a workaround that teams can do if they have a problem with that — they can add these lines in their index.tsx file:
```tsx
// @ts-ignore
Text.defaultProps = Text.defaultProps || {};
// @ts-ignore
Text.defaultProps.allowFontScaling = !DISABLE_FONT_SCALE;
// @ts-ignore
Text.defaultProps.maxFontSizeMultiplier = MAX_FONT_SCALE;
// @ts-ignore
Text.defaultProps.minimumFontScale = MIN_FONT_SCALE;
```

That will set the default props for anything based on the RN Text component to follow the scaling rules, but individual components can still override that behavior by setting props on them directly.

**Comment by daileytj** [comment]
Sounds good on the button side of things. @bkarambe can you look into the chevron issue? There should also be an update to the documentation to explain how to use the fontScaleProps. This would be a good place to explain the workaround @joebochill defined above.

**Comment by joebochill** [comment]
I told Suraj it was okay to hold off on adding anything to the documentation for this. It's not something I really want people doing and having it in your face in the Readme might give folks the wrong impression. I was thinking we could have a page dedicated to it when we do dev-docs for RN.

**Comment by surajeaton** [comment]
@joebochill @daileytj Ready for review

**Review by daileytj — APPROVED** [review]

**Pull request merged**
